version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - run:
          name: Deploy Over SSH
          addons:
            ssh_known_hosts:
             - actus@server.actus.cl
          command: |
            ssh actus@server.actus.cl "mkdir hola"
